//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int id_Customer { get; set; }
        public string RNC { get; set; }
        public string first_Name { get; set; }
        public string phone_Number { get; set; }
        public string email { get; set; }
        public string category { get; set; }
    }
}
